name: Test Orca IaC action

on:
  workflow_dispatch:

jobs:
  iac_scan_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan IaC
        uses: ./
        with:
          api_token:
            ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key:
            "default"
          path:
            "test"
          format:
            "sarif"
          output:
            "results/results.sarif"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: scan-results
          path: ./results/
